    [tool.ruff]
    # 设置目标 Python 版本 (可选, Ruff 会尝试自动检测)
    # target-version = "py310"

    # 选择启用的规则集 (E=pycodestyle errors, W=pycodestyle warnings, F=Pyflakes, I=isort, etc.)
    # 更多规则集请查阅 Ruff 文档
    select = ["E", "F", "W", "I", "UP"]

    # 忽略特定的规则 (例如 'E501' 是行太长)
    ignore = []

    # 你也可以配置 Linter 的具体规则
    [tool.ruff.lint]
    # 例如，设置允许的最大行长
    line-length = 88 # Black 默认值

    # 帮助 isort 识别你自己的项目模块
    [tool.ruff.lint.isort]
    known-first-party = ["core", "api"] # 把你的应用名加进去

    # 配置 Ruff 的格式化行为 (可选, Ruff 格式化器是实验性的但通常效果不错)
    [tool.ruff.format]
    # 例如，使用双引号而不是单引号
    quote-style = "double"
    # 是否在多行结尾添加逗号
    # trailing-comma = "all"